### PR TITLE
Updated & Optimized main function.

### PR DESCRIPTION
**Pull request by ghost**
Updated, Optimized & simplified the main function in main.py file.

### CODE REVIEW

**Comment by HarshitKumar9030** [comment]
ok this was abandoned tho , but thanks for reminding I'll work on this,
email me here, if you'd like too ceo@discoverthe.tech

**Comment by HarshitKumar9030** [comment]
marging!!

**Comment by ghost** [comment]
I am really sorry, there is a mistake with the import reference of time. I marked it time rather than t.

**Comment by HarshitKumar9030** [comment]
chill chill its fine

**Pull request merged**
